### ISSUE TITLE
Generating a translation file

### ISSUE THREAD

**Issue by AbelLykens** [Martinomagnifico/reveal.js-internation#1]
Great plugin, exactly what I was looking for. Using it for https://github.com/storingbitcoin-info/website . 

Was wonder if you considered a script that extracts strings from HTML and generates a json/translation file?

**Comment by Martinomagnifico** [comment]
Hi Abel, it is already included. You first need to tag the existing texts with a data-attribute in advance. After that, it is simply doing 2 things: set the 'makejson' option to true. Then load the page with an URL parameter of ?makejson appended to the URL. This will then download the json of the current HTML.

You do need to run a local server to do this by the way. I tested it with your website and it simply works. Don't forget to empty the browser cache when loading your new nl.json.

**Comment by AbelLykens** [comment]
That is very cool. And it works very well. Thanks a lot!
