### ISSUE TITLE
Minimal Working Example

### ISSUE THREAD

**Issue by Kaszanas** [Martinomagnifico/reveal.js-internation#4]
Hello,

I have attempted to run internation with one of my presentations, unfortunately I was unable to set it up in any usable way.

Could the authors of this plugin provide a minimal working example of how to properly set it up?

The hosted example works well but I was unable to run it locally.

Most of the issues I had were with the language selection menu, that throwed errors when attempting to switch between languages.

**Comment by Martinomagnifico** [comment]
Hi Andrzej, could you send me a small example of the presentation you would like to use Internation with? Or maybe you want to set up a teams/zoom meeting or something like that. That'll help me to figure out where it goes wrong.

**Comment by Kaszanas** [comment]
Sure! I am up for both, unfortunately I have removed internation from my current presentation so I will add it once again and I can Send over the error message I get in the Chrome console.

It might take me some time to do that.

**Comment by Martinomagnifico** [comment]
Did you try it out again? A probable cause could be that the presentation was run from the filesystem. When loading languages from external json files, it really needs a server (or localhost, running from ‘npm start’). If you really want to run it from the filesystem, you’ll need to add the needed language(s) directly into the Internation config, as documented.
