### ISSUE TITLE
How do you deal with the overflow of text to the newline if a translated language is longer than the original?

### ISSUE THREAD

**Issue by rockyhuber** [Martinomagnifico/reveal.js-internation#5]
Firstly thank you for the effort with this plugin.

We are going to use auto translations of the JSON, and not have the ability to check each slides CSS prior to translation... I translated one JSON file to French and it dropped to the next line on many slides, looking like the image attached. Any suggestions? Original in English below:
<img width="953" alt="image" src="https://github.com/Martinomagnifico/reveal.js-internation/assets/4715314/f62344cb-f79d-4098-961a-36bd997b48a5">
<img width="566" alt="image" src="https://github.com/Martinomagnifico/reveal.js-internation/assets/4715314/6ce2ca5b-f3f3-45ef-b6b1-2c93504a3d33">

**Comment by Martinomagnifico** [comment]
Three solutions:
1: Make sure that the codeblock are positioned relatively. Longer text will push the codeblock down. That is then just the way it is.
2: Same as 1, but make the h1 smaller. See https://codepen.io/martino/pen/ZEZQKRx. You could also use the h1 for the title of the deck and use h2's here. This would be my preferred solution.
3: Make the h1 fit the width of the slide with the 'r-fit-text' class that Reveal has. See https://codepen.io/martino/pen/dyLGRmp. There's an added script that re-layouts the slide after the text swap. Disadvantage is that the texts may get enormous or tiny.

**Comment by Martinomagnifico** [comment]
Did any of these solve the problem? It is, historically, a very old issue. Books, magazines etcetera. In those fields the translator gets the assignment to limit the amount of text and reword it if the text gets too long. This plugin may not need to be the issue-solver. 😀

**Comment by rockyhuber** [comment]
Thank you for your quick reply!

Right still working on it. Slides.com exports the divs in absolute position on the page. Which is why this is occurring. We have 1000's of slides that we're thinking about converting to slides.com, and then exporting to reveal.js. The export does it that way. Unfortunately the people creating the slides do not know HTML very well, so trying to come up with a solution that is easy enough for them to do without having to touch the code, which from where I sit doesn't look like it can happen. The aim was to build in slides.com, export into our platform, then automatically parse the code and add necessary attributes like "data-i18n", and automate as much of it as possible. Slides.com export to reveal.js just does it that way.

**Comment by rockyhuber** [comment]
I came up with a similar solution to option 3 you did above, but hacked it. And applied it to all "data-i18n" tags in throughout the deck. Let's say it made a lot of really small headings, really large lol.

**Comment by rockyhuber** [comment]
Just tried option 3 with class="r-fit-text", better result than what I hacked together :)

**Comment by rockyhuber** [comment]
So in saying that, yes I do not believe it is your plugin that needs to resolve it, thank you for your suggestions though!
